apiVersion: v1
kind: Secret
metadata:
  name: {{ include "animus-dataplane.secretsName" . }}
  labels:
    {{- include "animus-dataplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: dataplane
stringData:
  internalAuthSecret: {{ .Values.auth.internalAuthSecret | quote }}
