// Code generated by scripts/generate-gateway-client.go; DO NOT EDIT.
// Source: /home/guest/projects/animus-go/open/api/openapi/gateway.yaml

export type components = {
  schemas: {
    AuditEvent: { action: string; actor: string; event_id: number; integrity_sha256: string; ip?: string; occurred_at: string; payload: Record<string, unknown>; request_id?: string; resource_id: string; resource_type: string; user_agent?: string; };
    AuditEventListResponse: { events: (components["schemas"]["AuditEvent"])[]; next_before_event_id?: number; };
    AuthMeResponse: { email?: string; roles: (string)[]; user_id: string; };
    CIReportRequest: { commit_sha: string; image_digest: string; pipeline_id: string; provider?: string; repo: string; };
    CIReportResponse: { commit_sha?: string; image_digest: string; payload_sha256: string; pipeline_id?: string; provider?: string; received_at?: string; received_by?: string; repo?: string; status: "created" | "duplicate"; };
    CIWebhookRequest: { provider?: string; run_id: string; };
    CIWebhookResponse: { context_id: string; payload?: Record<string, unknown>; payload_sha256: string; provider?: string; received_at?: string; received_by?: string; run_id: string; status?: string; };
    CheckSpec: { allowed?: (string)[]; columns?: (string)[]; delimiter?: string; id: string; keys?: (string)[]; max_bytes?: number; min_bytes?: number; type: string; };
    CodeRef: { commitSha: string; path?: string; repoUrl: string; scmType?: string; };
    CreateDatasetRequest: { description?: string; metadata?: { }; name: string; };
    CreateEvaluationRequest: { dataset_version_id: string; rule_id?: string; };
    CreateEvidenceBundleResponse: { bundle: components["schemas"]["EvidenceBundle"]; };
    CreateExperimentRequest: { description?: string; metadata?: Record<string, unknown>; name: string; };
    CreateExperimentRunArtifactResponse: { artifact: components["schemas"]["ExperimentRunArtifact"]; };
    CreateExperimentRunEventRequest: { level?: "debug" | "info" | "warn" | "error"; message: string; metadata?: { }; occurred_at?: string; };
    CreateExperimentRunRequest: { artifacts_prefix?: string; dataset_version_id?: string; ended_at?: string; git_commit?: string; git_ref?: string; git_repo?: string; metrics?: Record<string, unknown>; params?: Record<string, unknown>; started_at?: string; status: "pending" | "running" | "succeeded" | "failed" | "canceled"; };
    CreatePolicyRequest: { description?: string; name: string; spec: string; status?: "active" | "disabled"; };
    CreatePolicyVersionRequest: { spec: string; status?: "active" | "disabled"; };
    CreateProjectRequest: { description?: string; metadata?: { }; name: string; };
    CreateRuleRequest: { description?: string; name: string; spec: components["schemas"]["RuleSpec"]; };
    Dataset: { created_at: string; created_by: string; dataset_id: string; description?: string; metadata: { }; name: string; };
    DatasetListResponse: { datasets: (components["schemas"]["Dataset"])[]; };
    DatasetVersion: { content_sha256: string; created_at: string; created_by: string; dataset_id: string; metadata: { }; object_key: string; ordinal: number; quality_rule_id?: string; size_bytes?: number; version_id: string; };
    DatasetVersionListResponse: { versions: (components["schemas"]["DatasetVersion"])[]; };
    DevEnvironment: { commitPin?: string; createdAt: string; createdBy?: string; devEnvId: string; dpJobName?: string; dpNamespace?: string; expiresAt: string; imageName: string; imageRef: string; integritySha256?: string; lastAccessAt?: string; policySnapshotSha256?: string; projectId: string; refType: components["schemas"]["DevEnvironmentRefType"]; refValue: string; repoUrl: string; state: components["schemas"]["DevEnvironmentState"]; templateDefinitionId?: string; templateIntegritySha256?: string; templateRef: string; templateVersion: number; ttlSeconds: number; };
    DevEnvironmentAccessRequest: { ttlSeconds?: number; };
    DevEnvironmentAccessResponse: { devEnvId: string; expiresAt: string; message?: string; projectId: string; proxyPath: string; sessionId: string; status?: string; };
    DevEnvironmentCreateRequest: { commitPin?: string; idempotencyKey?: string; imageName?: string; refType: components["schemas"]["DevEnvironmentRefType"]; refValue: string; repoUrl: string; templateRef: string; ttlSeconds?: number; };
    DevEnvironmentListResponse: { environments: (components["schemas"]["DevEnvironment"])[]; };
    DevEnvironmentRefType: "branch" | "tag" | "commit";
    DevEnvironmentResponse: { created: boolean; environment: components["schemas"]["DevEnvironment"]; };
    DevEnvironmentState: "provisioning" | "active" | "failed" | "expired" | "deleted";
    DryRunStepResult: { attempt: number; errorCode?: string; errorMessage?: string; finishedAt?: string; result?: { }; startedAt?: string; status: string; stepName: string; };
    EnvironmentBaseImage: { name: string; ref: string; };
    EnvironmentDefinition: { allowedAccelerators?: (string)[]; baseImages: (components["schemas"]["EnvironmentBaseImage"])[]; createdAt: string; createdBy?: string; description?: string; environmentDefinitionId: string; integritySha256?: string; metadata?: { [key: string]: string; }; name: string; networkClassRef?: string; projectId: string; resourceDefaults?: components["schemas"]["EnvironmentResources"]; resourceLimits?: components["schemas"]["EnvironmentResources"]; secretAccessClassRef?: string; status: string; supersedesDefinitionId?: string; version: number; };
    EnvironmentDefinitionCreateRequest: { allowedAccelerators?: (string)[]; baseImages: (components["schemas"]["EnvironmentBaseImage"])[]; description?: string; idempotencyKey?: string; metadata?: { [key: string]: string; }; name: string; networkClassRef?: string; resourceDefaults?: components["schemas"]["EnvironmentResources"]; resourceLimits?: components["schemas"]["EnvironmentResources"]; secretAccessClassRef?: string; };
    EnvironmentDefinitionListResponse: { definitions: (components["schemas"]["EnvironmentDefinition"])[]; };
    EnvironmentDefinitionResponse: { created: boolean; definition: components["schemas"]["EnvironmentDefinition"]; };
    EnvironmentDefinitionUpdateRequest: { allowedAccelerators?: (string)[]; baseImages?: (components["schemas"]["EnvironmentBaseImage"])[]; description?: string; idempotencyKey?: string; metadata?: { [key: string]: string; }; name?: string; networkClassRef?: string; resourceDefaults?: components["schemas"]["EnvironmentResources"]; resourceLimits?: components["schemas"]["EnvironmentResources"]; secretAccessClassRef?: string; };
    EnvironmentImage: { digest: string; name: string; ref: string; };
    EnvironmentLock: { allowedAccelerators?: (string)[]; createdAt?: string; createdBy?: string; dependencyChecksums?: { [key: string]: string; }; envHash: string; environmentDefinitionId: string; environmentDefinitionVersion: number; images: (components["schemas"]["EnvironmentImage"])[]; integritySha256?: string; lockId: string; networkClassRef?: string; projectId?: string; resourceDefaults?: components["schemas"]["EnvironmentResources"]; resourceLimits?: components["schemas"]["EnvironmentResources"]; sbomRef?: string; secretAccessClassRef?: string; };
    EnvironmentLockCreateRequest: { dependencyChecksums?: { [key: string]: string; }; environmentDefinitionId: string; idempotencyKey?: string; imageDigests: { [key: string]: string; }; sbomRef?: string; };
    EnvironmentLockListResponse: { locks: (components["schemas"]["EnvironmentLock"])[]; };
    EnvironmentLockRef: { lockId: string; };
    EnvironmentLockResponse: { created: boolean; lock: components["schemas"]["EnvironmentLock"]; };
    EnvironmentResources: { cpu?: string; gpu?: number; memory?: string; };
    ErrorResponse: { error: string; request_id: string; };
    Evaluation: { dataset_version_id: string; evaluated_at: string; evaluated_by: string; evaluation_id: string; report_object_key: string; report_sha256: string; report_size_bytes: number; rule_id: string; status: string; summary: components["schemas"]["EvaluationSummary"]; };
    EvaluationListResponse: { evaluations: (components["schemas"]["Evaluation"])[]; };
    EvaluationSummary: { checks_error: number; checks_fail: number; checks_pass: number; checks_total: number; failing_check_ids?: (string)[]; };
    EvidenceBundle: { bundle_id: string; bundle_object_key: string; bundle_sha256: string; bundle_size_bytes: number; created_at: string; created_by: string; report_object_key: string; report_sha256: string; report_size_bytes: number; run_id: string; signature: string; signature_alg: string; };
    EvidenceBundleListResponse: { bundles: (components["schemas"]["EvidenceBundle"])[]; };
    ExecuteExperimentRunPendingApprovalResponse: { approval_ids: (string)[]; approval_required: boolean; run_id: string; status: "pending"; };
    ExecuteExperimentRunRequest: { dataset_version_id: string; experiment_id: string; git_commit?: string; git_ref?: string; git_repo?: string; image_ref: string; params?: Record<string, unknown>; resources?: { }; };
    ExecuteExperimentRunResponse: { datapilot_url: string; execution_id: string; run_id: string; status: "pending" | "running"; };
    ExecutionLedgerEntry: { created_at: string; created_by: string; dataset: { dataset_id: string; sha256: string; version_id: string; }; execution_id: string; executor: { datapilot_url: string; docker_container_id?: string; k8s_job_name?: string; k8s_namespace?: string; kind: string; }; experiment_id: string; git?: { commit?: string; ref?: string; repo?: string; }; image: { digest: string; ref: string; }; ledger_id: string; params: { }; policy: { approvals?: (components["schemas"]["ExecutionLedgerPolicyApproval"])[]; decisions: (components["schemas"]["ExecutionLedgerPolicyDecision"])[]; }; resources: { }; run_id: string; schema: string; };
    ExecutionLedgerExportResponse: { checksum: string; entries: (components["schemas"]["ExecutionLedgerRecord"])[]; };
    ExecutionLedgerPolicyApproval: { approval_id: string; decided_at?: string; decided_by?: string; decision_id: string; reason?: string; requested_at: string; requested_by: string; status: "pending" | "approved" | "denied"; };
    ExecutionLedgerPolicyDecision: { context_sha256: string; created_at: string; created_by: string; decision: string; decision_id: string; policy_id: string; policy_sha256: string; policy_version_id: string; reason?: string; rule_id?: string; };
    ExecutionLedgerRecord: { created_at: string; created_by: string; entry: components["schemas"]["ExecutionLedgerEntry"]; entry_sha256: string; execution_hash: string; execution_id: string; ledger_id: string; replay_bundle: components["schemas"]["ExecutionReplayBundle"]; run_id: string; };
    ExecutionPlan: { };
    ExecutionReplayBundle: { dataset_id: string; dataset_sha256: string; dataset_version_id: string; executor: string; experiment_id: string; git_commit?: string; git_ref?: string; git_repo?: string; image_digest: string; image_ref: string; params: { }; resources: { }; run_id: string; schema: string; };
    Experiment: { created_at: string; created_by: string; description?: string; experiment_id: string; metadata: Record<string, unknown>; name: string; };
    ExperimentListResponse: { experiments: (components["schemas"]["Experiment"])[]; };
    ExperimentRun: { artifacts_prefix?: string; dataset_version_id?: string; ended_at?: string; experiment_id: string; git_commit?: string; git_ref?: string; git_repo?: string; metrics: Record<string, unknown>; params: Record<string, unknown>; run_id: string; started_at: string; status: "pending" | "running" | "succeeded" | "failed" | "canceled"; };
    ExperimentRunArtifact: { artifact_id: string; content_type?: string; created_at: string; created_by: string; filename?: string; kind: "model" | "preview" | "log" | "file"; metadata: Record<string, unknown>; name?: string; object_key: string; run_id: string; sha256: string; size_bytes: number; };
    ExperimentRunArtifactListResponse: { artifacts: (components["schemas"]["ExperimentRunArtifact"])[]; };
    ExperimentRunBuildContext: { commit_sha?: string; image_digest?: string; image_ref: string; pipeline_id?: string; provider?: string; received_at?: string; repo?: string; run_id: string; };
    ExperimentRunEvent: { actor: string; event_id: number; level: string; message: string; metadata: { }; occurred_at: string; run_id: string; };
    ExperimentRunEventListResponse: { events: (components["schemas"]["ExperimentRunEvent"])[]; next_before_event_id?: number; run_id: string; };
    ExperimentRunExecution: { created_at: string; created_by: string; datapilot_url: string; docker_container_id?: string; execution_id: string; executor: string; image_digest?: string; image_ref: string; k8s_job_name?: string; k8s_namespace?: string; resources: { }; run_id: string; };
    ExperimentRunListResponse: { runs: (components["schemas"]["ExperimentRun"])[]; };
    ExperimentRunMetricSample: { metadata: { }; name: string; recorded_at: string; recorded_by: string; run_id: string; sample_id: string; step: number; value: number; };
    ExperimentRunMetricsResponse: { name?: string; run_id: string; samples: (components["schemas"]["ExperimentRunMetricSample"])[]; };
    ExportAttempt: { attempt_id: number; attempted_at: string; created_at: string; delivery_id: number; error?: string; latency_ms?: number; outcome: string; status_code?: number; };
    ExportAttemptListResponse: { attempts: (components["schemas"]["ExportAttempt"])[]; };
    ExportDelivery: { attempt_count: number; created_at: string; delivered_at?: string; delivery_id: number; dlq_reason?: string; event_id: number; last_error?: string; next_attempt_at: string; sink_id: string; status: string; updated_at: string; };
    ExportDeliveryListResponse: { deliveries: (components["schemas"]["ExportDelivery"])[]; };
    ExportReplayRequest: { replay_token?: string; };
    ExportReplayResponse: { status: string; };
    ExportSink: { config: components["schemas"]["ExportSinkConfig"]; created_at: string; destination: string; enabled: boolean; format: string; name: string; sink_id: string; updated_at: string; };
    ExportSinkConfig: { syslog_addr?: string; syslog_protocol?: string; syslog_tag?: string; webhook_secret_ref?: string; webhook_signing_key?: string; webhook_url?: string; };
    ExportSinkListResponse: { sinks: (components["schemas"]["ExportSink"])[]; };
    ForceLogoutRequest: { reason?: string; session_id?: string; subject?: string; };
    ForceLogoutResponse: { revoked: number; };
    GateStatus: { dataset_version_id: string; evaluated_at?: string; evaluation_id?: string; rule_id?: string; status: string; };
    GitlabGovernanceRecord: { approvals_approved?: boolean; approvals_received?: number; approvals_required?: number; commit_sha: string; event_type: string; governance_id: string; merge_request_id?: number; merge_request_iid?: number; merge_request_source_branch?: string; merge_request_target_branch?: string; merge_request_url?: string; payload_sha256: string; pipeline_id?: number; pipeline_source?: string; pipeline_status?: string; pipeline_url?: string; project_id?: number; project_path?: string; received_at: string; received_by: string; ref?: string; ref_protected?: boolean; repo: string; signature: string; };
    GitlabWebhookPayload: { };
    GitlabWebhookResponse: { record: components["schemas"]["GitlabGovernanceRecord"]; status: "created" | "duplicate"; };
    HealthResponse: { service: string; status: string; };
    ImageVerificationListResponse: { items: (components["schemas"]["ImageVerificationRecord"])[]; };
    ImageVerificationRecord: { createdAt: string; details?: { }; failureReason?: string; imageDigestRef: string; policyMode: components["schemas"]["RegistryPolicyMode"]; projectId: string; provider: string; signed: boolean; status: string; verified: boolean; verifiedAt?: string; };
    IngestExperimentRunMetricsRequest: { metadata?: { }; metrics: { }; step: number; };
    IngestExperimentRunMetricsResponse: { inserted: number; received: number; request_id: string; run_id: string; step: number; };
    LineageEvent: { actor: string; event_id: number; metadata: Record<string, unknown>; object_id: string; object_type: string; occurred_at: string; predicate: string; request_id?: string; subject_id: string; subject_type: string; };
    LineageEventListResponse: { events: (components["schemas"]["LineageEvent"])[]; next_before_event_id?: number; };
    LineageNode: { id: string; type: string; };
    Model: { artifactId?: string; createdAt: string; createdBy?: string; integritySha256?: string; metadata?: Record<string, unknown>; modelId: string; name: string; projectId: string; status: components["schemas"]["ModelStatus"]; version: string; };
    ModelCreateRequest: { idempotencyKey?: string; metadata?: Record<string, unknown>; name: string; };
    ModelCreateResponse: { created: boolean; model: components["schemas"]["Model"]; };
    ModelExport: { createdAt: string; createdBy?: string; exportId: string; integritySha256?: string; modelVersionId: string; projectId: string; status: string; target?: string; };
    ModelExportRequest: { target?: string; };
    ModelExportResponse: { created: boolean; export: components["schemas"]["ModelExport"]; };
    ModelImage: { commit_sha: string; image_digest: string; payload?: Record<string, unknown>; pipeline_id: string; provider?: string; received_at: string; received_by: string; repo: string; };
    ModelImageListResponse: { model_images: (components["schemas"]["ModelImage"])[]; };
    ModelListResponse: { models: (components["schemas"]["Model"])[]; };
    ModelStatus: "draft" | "validated" | "approved" | "deprecated";
    ModelVersion: { artifactIds: (string)[]; codeRef?: components["schemas"]["CodeRef"]; createdAt: string; createdBy?: string; datasetVersionIds?: (string)[]; envLockId?: string; integritySha256?: string; modelId: string; modelVersionId: string; policySnapshotSha256?: string; projectId: string; runId: string; status: components["schemas"]["ModelStatus"]; version: string; };
    ModelVersionCreateRequest: { artifactIds: (string)[]; datasetVersionIds?: (string)[]; idempotencyKey?: string; runId: string; version: string; };
    ModelVersionCreateResponse: { created: boolean; modelVersion: components["schemas"]["ModelVersion"]; };
    ModelVersionListResponse: { modelVersions: (components["schemas"]["ModelVersion"])[]; };
    ModelVersionProvenanceResponse: { artifactIds: (string)[]; codeRef?: components["schemas"]["CodeRef"]; datasetVersionIds?: (string)[]; envLockId?: string; modelId: string; modelVersionId: string; policySnapshotSha256?: string; projectId: string; runId: string; version: string; };
    ModelVersionTransitionResponse: { modelVersion: components["schemas"]["ModelVersion"]; };
    PolicyApprovalActionRequest: { reason?: string; };
    PolicyApprovalActionResponse: { approval_id: string; approval_status: "pending" | "approved" | "denied"; datapilot_url?: string; execution_id?: string; pending?: number; run_id: string; run_status: "pending" | "running" | "canceled"; };
    PolicyApprovalDetail: components["schemas"]["PolicyApprovalSummary"] & { decision_context?: { }; };
    PolicyApprovalListResponse: { approvals: (components["schemas"]["PolicyApprovalSummary"])[]; };
    PolicyApprovalSummary: { approval_id: string; decided_at?: string; decided_by?: string; decision: "allow" | "deny" | "require_approval"; decision_id: string; policy_id: string; policy_name: string; policy_version_id: string; reason?: string; requested_at: string; requested_by: string; rule_id?: string; run_id?: string; status: "pending" | "approved" | "denied"; };
    PolicyDecisionDetail: components["schemas"]["PolicyDecisionSummary"] & { context: { }; };
    PolicyDecisionListResponse: { decisions: (components["schemas"]["PolicyDecisionSummary"])[]; };
    PolicyDecisionSummary: { context_sha256: string; created_at: string; created_by: string; decision: "allow" | "deny" | "require_approval"; decision_id: string; policy_id: string; policy_name?: string; policy_sha256: string; policy_version_id: string; reason?: string; rule_id?: string; run_id?: string; };
    PolicyListResponse: { policies: (components["schemas"]["PolicySummary"])[]; };
    PolicySnapshot: { capturedAt: string; capturedBy?: string; network?: components["schemas"]["PolicySnapshotNetwork"]; policies: (components["schemas"]["PolicySnapshotPolicy"])[]; rbac: components["schemas"]["PolicySnapshotRBAC"]; retention?: components["schemas"]["PolicySnapshotRetention"]; secrets?: components["schemas"]["PolicySnapshotSecrets"]; snapshotSha256: string; snapshotVersion: string; templates?: components["schemas"]["PolicySnapshotTemplates"]; };
    PolicySnapshotNetwork: { allowlist?: (string)[]; classRef?: string; denylist?: (string)[]; mode: string; };
    PolicySnapshotPolicy: { policyId: string; policyName?: string; policySha256: string; policyVersion?: number; policyVersionId: string; status: string; };
    PolicySnapshotRBAC: { decision?: string; projectId: string; roles: (string)[]; subject: string; };
    PolicySnapshotRetention: { legalHold?: boolean; mode: string; policyId?: string; policySha256?: string; policyVersionId?: string; };
    PolicySnapshotSecrets: { classRef?: string; mode: string; };
    PolicySnapshotTemplates: { allowedTemplateIds?: (string)[]; mode: string; };
    PolicySummary: { created_at: string; created_by: string; description?: string; latest_version?: components["schemas"]["PolicyVersionSummary"]; name: string; policy_id: string; };
    PolicyVersion: { created_at: string; created_by: string; policy_id: string; policy_version_id: string; spec: { }; spec_sha256: string; spec_yaml: string; status: "active" | "disabled"; version: number; };
    PolicyVersionListResponse: { policy_id: string; versions: (components["schemas"]["PolicyVersion"])[]; };
    PolicyVersionSummary: { created_at: string; created_by: string; policy_version_id: string; spec_sha256: string; status: "active" | "disabled"; version: number; };
    Project: { created_at: string; created_by: string; description?: string; metadata: { }; name: string; project_id: string; };
    ProjectListResponse: { projects: (components["schemas"]["Project"])[]; };
    ProjectRunCreateRequest: { codeRef: components["schemas"]["CodeRef"]; datasetBindings: { [key: string]: string; }; envLock: components["schemas"]["EnvironmentLockRef"]; idempotencyKey?: string; parameters: { }; pipelineSpec: { }; };
    ProjectRunCreateResponse: { created: boolean; runId: string; specHash: string; status: string; };
    ProjectRunDispatchRequest: { idempotencyKey?: string; };
    ProjectRunDispatchResponse: { created: boolean; dispatchId: string; dpBaseUrl: string; projectId: string; runId: string; status: string; };
    ProjectRunDryRunExecutionsResponse: { attemptsByStep?: { [key: string]: number; }; executions: (components["schemas"]["ProjectRunStepExecution"])[]; planExists: boolean; runId: string; state: string; };
    ProjectRunDryRunResponse: { attemptsByStep?: { [key: string]: number; }; existing: boolean; runId: string; state: string; status: string; steps: (components["schemas"]["DryRunStepResult"])[]; };
    ProjectRunGetResponse: { attemptsByStep?: { [key: string]: number; }; createdAt: string; planExists: boolean; runId: string; runSpec: components["schemas"]["RunSpec"]; specHash: string; state: string; status: string; };
    ProjectRunPlanSummary: { runId: string; state: string; stepCount: number; stepNames: (string)[]; };
    ProjectRunReproducibilityBundle: { generatedAt: string; generatedBy?: string; policySnapshotSha256: string; projectId: string; runId: string; runSpec: components["schemas"]["RunSpec"]; schema: string; specHash: string; };
    ProjectRunStepExecution: { attempt: number; errorCode?: string; errorMessage?: string; finishedAt?: string; result?: { }; startedAt: string; status: string; stepName: string; };
    QualityRule: { created_at: string; created_by: string; description?: string; name: string; rule_id: string; spec: components["schemas"]["RuleSpec"]; };
    RegistryPolicyMode: "allow_unsigned" | "deny_unsigned" | "verify_only";
    RoleBinding: { binding_id: string; created_at: string; created_by: string; project_id: string; role: "viewer" | "editor" | "admin"; subject: string; subject_type: "subject" | "email" | "group" | "service"; updated_at: string; updated_by: string; };
    RoleBindingListResponse: { bindings: (components["schemas"]["RoleBinding"])[]; };
    RoleBindingRequest: { role: "viewer" | "editor" | "admin"; subject: string; subject_type: "subject" | "email" | "group" | "service"; };
    RoleBindingResponse: { binding: components["schemas"]["RoleBinding"]; created: boolean; };
    RuleListResponse: { rules: (components["schemas"]["QualityRule"])[]; };
    RuleSpec: { checks: (components["schemas"]["CheckSpec"])[]; schema: string; };
    RunSpec: { codeRef: components["schemas"]["CodeRef"]; createdAt: string; createdBy?: string; datasetBindings: { [key: string]: string; }; envLock: components["schemas"]["EnvironmentLock"]; parameters: { }; pipelineSpec: { }; policySnapshot: components["schemas"]["PolicySnapshot"]; projectId: string; runSpecVersion: string; };
    SessionResponse: { email: string; roles: (string)[]; subject: string; };
    StatusResponse: { status: string; };
    SubgraphResponse: { edges: (components["schemas"]["LineageEvent"])[]; nodes: (components["schemas"]["LineageNode"])[]; root: components["schemas"]["LineageNode"]; };
    WebhookDelivery: { attempt_count: number; created_at: string; event_id: string; event_type: components["schemas"]["WebhookEventType"]; id: string; last_error?: string; next_attempt_at: string; project_id: string; status: components["schemas"]["WebhookDeliveryStatus"]; subscription_id: string; updated_at: string; };
    WebhookDeliveryAttempt: { attempted_at: string; created_at: string; delivery_id: string; error?: string; id: number; latency_ms?: number; outcome: string; request_id?: string; status_code?: number; };
    WebhookDeliveryAttemptListResponse: { attempts: (components["schemas"]["WebhookDeliveryAttempt"])[]; };
    WebhookDeliveryListResponse: { deliveries: (components["schemas"]["WebhookDelivery"])[]; };
    WebhookDeliveryReplayRequest: { replay_token: string; };
    WebhookDeliveryReplayResponse: { delivery_id: string; scheduled: boolean; };
    WebhookDeliveryStatus: "PENDING" | "DELIVERED" | "FAILED" | "DISABLED";
    WebhookEventPayload: { api_links?: { [key: string]: string; }; emitted_at: string; event_id: string; event_type: components["schemas"]["WebhookEventType"]; project_id: string; subject: components["schemas"]["WebhookEventSubject"]; };
    WebhookEventSubject: { dataset_version_id?: string; model_version_id?: string; run_id?: string; };
    WebhookEventType: "RunFinished" | "ModelApproved" | "DatasetVersionCreated";
    WebhookSubscriptionCreateRequest: { enabled?: boolean; event_types: (components["schemas"]["WebhookEventType"])[]; headers?: { [key: string]: string; }; name: string; secret_ref?: string; target_url: string; };
    WebhookSubscriptionListResponse: { subscriptions: (components["schemas"]["WebhookSubscriptionResponse"])[]; };
    WebhookSubscriptionResponse: { created_at: string; enabled: boolean; event_types: (components["schemas"]["WebhookEventType"])[]; headers?: { [key: string]: string; }; id: string; name: string; project_id: string; secret_ref?: string; target_url: string; updated_at: string; };
    WebhookSubscriptionUpdateRequest: { enabled?: boolean; event_types?: (components["schemas"]["WebhookEventType"])[]; headers?: { [key: string]: string; }; name?: string; secret_ref?: string; target_url?: string; };
  }
}

export type operations = {
  "delete__api_audit_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "delete__api_dataset_registry_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "delete__api_experiments_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "delete__api_lineage_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "delete__api_quality_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayApproveModelVersion": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersionTransitionResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
      409: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayCreateModel": {
    parameters: {
      path: {
        project_id: string;
      };
      header?: {
        Idempotency_Key: string;
      };
    };
    requestBody?: components["schemas"]["ModelCreateRequest"];
    responses: {
      200: components["schemas"]["ModelCreateResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayCreateModelVersion": {
    parameters: {
      path: {
        model_id: string;
        project_id: string;
      };
      header?: {
        Idempotency_Key: string;
      };
    };
    requestBody?: components["schemas"]["ModelVersionCreateRequest"];
    responses: {
      200: components["schemas"]["ModelVersionCreateResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayDeprecateModelVersion": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersionTransitionResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
      409: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayExportModelVersion": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
      header?: {
        Idempotency_Key: string;
      };
    };
    requestBody?: components["schemas"]["ModelExportRequest"];
    responses: {
      200: components["schemas"]["ModelExportResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
      409: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayGetModel": {
    parameters: {
      path: {
        model_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["Model"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayGetModelVersion": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersion"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayGetModelVersionProvenance": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersionProvenanceResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayListModelVersions": {
    parameters: {
      path: {
        model_id: string;
        project_id: string;
      };
      query?: {
        limit?: number;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersionListResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayListModels": {
    parameters: {
      path: {
        project_id: string;
      };
      query?: {
        limit?: number;
        name?: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelListResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
    };
  };
  "gatewayValidateModelVersion": {
    parameters: {
      path: {
        model_version_id: string;
        project_id: string;
      };
    };
    requestBody?: never;
    responses: {
      200: components["schemas"]["ModelVersionTransitionResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      404: components["schemas"]["ErrorResponse"];
      409: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_audit_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_auth_me": {
    parameters?: never;
    requestBody?: never;
    responses: {
      200: components["schemas"]["AuthMeResponse"];
      401: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_dataset_registry_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_experiments_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_lineage_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "get__api_quality_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "get__auth_callback": {
    parameters: {
      query?: {
        code: string;
        state: string;
      };
    };
    requestBody?: never;
    responses: {
      302: unknown;
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      501: components["schemas"]["ErrorResponse"];
    };
  };
  "get__auth_login": {
    parameters: {
      query?: {
        return_to?: string;
      };
    };
    requestBody?: never;
    responses: {
      302: unknown;
      501: components["schemas"]["ErrorResponse"];
    };
  };
  "get__auth_session": {
    parameters?: never;
    requestBody?: never;
    responses: {
      200: components["schemas"]["SessionResponse"];
      401: components["schemas"]["ErrorResponse"];
    };
  };
  "get__healthz": {
    parameters?: never;
    requestBody?: never;
    responses: {
      200: components["schemas"]["HealthResponse"];
    };
  };
  "get__readyz": {
    parameters?: never;
    requestBody?: never;
    responses: {
      200: components["schemas"]["HealthResponse"];
    };
  };
  "patch__api_audit_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "patch__api_dataset_registry_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "patch__api_experiments_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "patch__api_lineage_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "patch__api_quality_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__api_audit_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__api_dataset_registry_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__api_experiments_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__api_lineage_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__api_quality_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "post__auth_force_logout": {
    parameters?: never;
    requestBody?: components["schemas"]["ForceLogoutRequest"];
    responses: {
      200: components["schemas"]["ForceLogoutResponse"];
      400: components["schemas"]["ErrorResponse"];
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
    };
  };
  "post__auth_logout": {
    parameters?: never;
    requestBody?: never;
    responses: {
      200: components["schemas"]["StatusResponse"];
    };
  };
  "put__api_audit_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "put__api_dataset_registry_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "put__api_experiments_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "put__api_lineage_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
  "put__api_quality_proxyPath": {
    parameters: {
      path: {
        proxyPath: string;
      };
    };
    requestBody?: never;
    responses: {
      200: { };
      401: components["schemas"]["ErrorResponse"];
      403: components["schemas"]["ErrorResponse"];
      502: components["schemas"]["ErrorResponse"];
    };
  };
}

export type paths = {
  "/api/audit/{proxyPath}": {
    get?: operations["get__api_audit_proxyPath"];
    post?: operations["post__api_audit_proxyPath"];
    put?: operations["put__api_audit_proxyPath"];
    patch?: operations["patch__api_audit_proxyPath"];
    delete?: operations["delete__api_audit_proxyPath"];
  };
  "/api/auth/me": {
    get?: operations["get__api_auth_me"];
  };
  "/api/dataset-registry/{proxyPath}": {
    get?: operations["get__api_dataset_registry_proxyPath"];
    post?: operations["post__api_dataset_registry_proxyPath"];
    put?: operations["put__api_dataset_registry_proxyPath"];
    patch?: operations["patch__api_dataset_registry_proxyPath"];
    delete?: operations["delete__api_dataset_registry_proxyPath"];
  };
  "/api/experiments/{proxyPath}": {
    get?: operations["get__api_experiments_proxyPath"];
    post?: operations["post__api_experiments_proxyPath"];
    put?: operations["put__api_experiments_proxyPath"];
    patch?: operations["patch__api_experiments_proxyPath"];
    delete?: operations["delete__api_experiments_proxyPath"];
  };
  "/api/lineage/{proxyPath}": {
    get?: operations["get__api_lineage_proxyPath"];
    post?: operations["post__api_lineage_proxyPath"];
    put?: operations["put__api_lineage_proxyPath"];
    patch?: operations["patch__api_lineage_proxyPath"];
    delete?: operations["delete__api_lineage_proxyPath"];
  };
  "/api/quality/{proxyPath}": {
    get?: operations["get__api_quality_proxyPath"];
    post?: operations["post__api_quality_proxyPath"];
    put?: operations["put__api_quality_proxyPath"];
    patch?: operations["patch__api_quality_proxyPath"];
    delete?: operations["delete__api_quality_proxyPath"];
  };
  "/auth/callback": {
    get?: operations["get__auth_callback"];
  };
  "/auth/force-logout": {
    post?: operations["post__auth_force_logout"];
  };
  "/auth/login": {
    get?: operations["get__auth_login"];
  };
  "/auth/logout": {
    post?: operations["post__auth_logout"];
  };
  "/auth/session": {
    get?: operations["get__auth_session"];
  };
  "/healthz": {
    get?: operations["get__healthz"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}": {
    get?: operations["gatewayGetModelVersion"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}/provenance": {
    get?: operations["gatewayGetModelVersionProvenance"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}:approve": {
    post?: operations["gatewayApproveModelVersion"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}:deprecate": {
    post?: operations["gatewayDeprecateModelVersion"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}:export": {
    post?: operations["gatewayExportModelVersion"];
  };
  "/projects/{project_id}/model-versions/{model_version_id}:validate": {
    post?: operations["gatewayValidateModelVersion"];
  };
  "/projects/{project_id}/models": {
    get?: operations["gatewayListModels"];
    post?: operations["gatewayCreateModel"];
  };
  "/projects/{project_id}/models/{model_id}": {
    get?: operations["gatewayGetModel"];
  };
  "/projects/{project_id}/models/{model_id}/versions": {
    get?: operations["gatewayListModelVersions"];
    post?: operations["gatewayCreateModelVersion"];
  };
  "/readyz": {
    get?: operations["get__readyz"];
  };
}
